import { test, expect } from '@playwright/test';

test('桌面真实三维渲染、驾驶、炮击和暂停', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  if (process.env.CI) await page.addInitScript(() => localStorage.setItem('tb-quality', 'low'));
  await page.goto('./');
  await expect(page.locator('#soloButton')).toBeVisible();
  await page.waitForFunction(() => (window as any).__tankBattle?.fps > 0);
  await page.screenshot({ path: 'artifacts/desktop-menu.png' });
  await page.getByRole('button', { name: '开始单人战役' }).click();
  await expect(page.locator('#hud')).toBeVisible();
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.phase)).toBe('battle');
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.camera.position.y)).toBeGreaterThan(11);
  const initial = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0]);
  // 只按左键就应产生横向位移，不依赖前进键，炮塔仍对准原来的瞄准方向。
  await page.keyboard.down('KeyA');
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.tanks[0].x)).toBeGreaterThan(initial.x + 1.2);
  await page.keyboard.up('KeyA');
  const left = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0]);
  expect(left.z).toBeCloseTo(initial.z);
  expect(left.turret).toBeCloseTo(initial.turret);
  const before = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0].z);
  await page.keyboard.down('KeyW');
  // 等待实际移动结果，避免 CI 软件渲染速度影响固定墙钟延迟的断言。
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.tanks[0].z)).toBeLessThan(before - 1.5);
  await page.keyboard.up('KeyW');
  const after = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0].z);
  expect(after).toBeLessThan(before - 1);
  await page.keyboard.down('Space');
  await page.waitForTimeout(1600);
  await page.keyboard.up('Space');
  expect(await page.evaluate(() => (window as any).__tankBattle.state.events.some((e: any) => e.kind === 'shot'))).toBe(true);
  await page.screenshot({ path: 'artifacts/desktop-battle.png' });
  await page.getByRole('button', { name: '暂停', exact: true }).click();
  await expect(page.locator('#pauseDialog')).toBeVisible();
  const time = await page.evaluate(() => (window as any).__tankBattle.state.time);
  await page.waitForTimeout(350);
  expect(await page.evaluate(() => (window as any).__tankBattle.state.time)).toBe(time);
  await page.getByRole('button', { name: '继续战斗' }).click();
  await expect(page.locator('#pauseDialog')).not.toBeVisible();
  await page.mouse.wheel(0, 10000);
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.camera.zoom)).toBe(30);
  await page.keyboard.press('KeyC');
  const reset = await page.evaluate(() => (window as any).__tankBattle.camera);
  expect(reset.zoom).toBe(18);
  expect(reset.pitch).toBe(0.7);
  expect(errors).toEqual([]);
});

test('手机竖屏、横屏和双拇指输入', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.locator('#soloButton')).toBeVisible();
  await page.waitForFunction(() => (window as any).__tankBattle?.fps > 0);
  await page.screenshot({ path: 'artifacts/mobile-menu.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#soloButton').tap();
  await expect(page.locator('#joystick')).toBeVisible();
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.phase)).toBe('battle');
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.camera.position.y)).toBeGreaterThan(13);
  const before = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0]);
  const cdp = await context.newCDPSession(page);
  const stick = (await page.locator('#joystick').boundingBox())!;
  const fire = (await page.locator('#fireButton').boundingBox())!;
  const left = { x: stick.x + 12, y: stick.y + stick.height / 2, id: 1 };
  const right = { x: fire.x + fire.width / 2, y: fire.y + fire.height / 2, id: 2 };
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [left] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [left, right] });
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.tanks[0].x)).toBeGreaterThan(before.x + 1.2);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const moved = await page.evaluate(() => (window as any).__tankBattle.state.tanks[0]);
  expect(moved.z).toBeCloseTo(before.z);
  // 松开摇杆后旋转镜头，再次向左推；位移应跟随新的画面左侧。
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [right] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ ...right, x: right.x - 100 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const rotated = await page.evaluate(() => (window as any).__tankBattle);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [left] });
  await expect.poll(() => page.evaluate(() => (window as any).__tankBattle.state.tanks[0].x)).toBeGreaterThan(moved.x + 1);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const diagnostics = await page.evaluate(() => (window as any).__tankBattle);
  const dx = diagnostics.state.tanks[0].x - rotated.state.tanks[0].x;
  const dz = diagnostics.state.tanks[0].z - rotated.state.tanks[0].z;
  expect(dz / dx).toBeCloseTo(-Math.tan(rotated.camera.yaw), 1);
  expect(Math.abs(diagnostics.camera.yaw - Math.PI)).toBeGreaterThan(0.1);
  expect(diagnostics.state.events.some((e: any) => e.kind === 'shot')).toBe(true);
  await page.screenshot({ path: 'artifacts/mobile-portrait.png' });
  await page.setViewportSize({ width: 844, height: 390 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/mobile-landscape.png' });
  for (const selector of ['#joystick', '#fireButton', '#pauseButton']) {
    const rect = (await page.locator(selector).boundingBox())!;
    expect(rect.x).toBeGreaterThanOrEqual(0);
    expect(rect.y).toBeGreaterThanOrEqual(0);
    expect(rect.x + rect.width).toBeLessThanOrEqual(844);
    expect(rect.y + rect.height).toBeLessThanOrEqual(390);
  }
  expect(errors).toEqual([]);
  await context.close();
});

test('手机创建房间，第二位玩家通过真实 WebRTC 同步战场', async ({ browser }) => {
  test.setTimeout(100000);
  const hostContext = await browser.newContext({ viewport: { width: 844, height: 390 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const guestContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const host = await hostContext.newPage();
  const guest = await guestContext.newPage();
  const errors: string[] = [];
  host.on('pageerror', e => errors.push(e.message));
  guest.on('pageerror', e => errors.push(e.message));
  await host.goto('./');
  await host.locator('#playerName').fill('房主坦克');
  await host.locator('#hostButton').tap();
  await expect(host.locator('#lobbyDialog')).toBeVisible({ timeout: 25000 });
  const code = (await host.locator('#roomCode').textContent())!;
  expect(code).toMatch(/^[A-Z2-9]{6}$/);
  await host.screenshot({ path: 'artifacts/mobile-lobby.png' });
  await guest.goto('./?room=' + code);
  await guest.locator('#connectButton').tap();
  await expect(guest.locator('#lobbyDialog')).toBeVisible({ timeout: 45000 });
  await guest.locator('#readyButton').tap();
  await expect(host.locator('#startRoom')).toBeEnabled();
  await host.locator('#startRoom').tap();
  await expect(guest.locator('#hud')).toBeVisible();
  await expect.poll(() => guest.evaluate(() => (window as any).__tankBattle.state.tanks.filter((t: any) => t.team === 'player').length)).toBe(2);
  await expect.poll(() => guest.evaluate(() => (window as any).__tankBattle.state.phase), { timeout: 15000 }).toBe('battle');
  const hostState = await host.evaluate(() => (window as any).__tankBattle.state);
  const guestState = await guest.evaluate(() => (window as any).__tankBattle.state);
  expect(hostState.seed).toBe(guestState.seed);
  expect(hostState.obstacles).toEqual(guestState.obstacles);
  const guestBefore = await guest.evaluate(() => {
    const d = (window as any).__tankBattle;
    return d.state.tanks.find((t: any) => t.id === d.localId);
  });
  const cdp = await guestContext.newCDPSession(guest);
  const stick = (await guest.locator('#joystick').boundingBox())!;
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: stick.x + 12, y: stick.y + stick.height / 2, id: 1 }] });
  await expect.poll(() => host.evaluate(() => (window as any).__tankBattle.state.tanks.find((t: any) => t.team === 'player' && t.name !== '房主坦克').x)).toBeGreaterThan(guestBefore.x + 1);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await guest.waitForTimeout(600);
  const hostGuest = await host.evaluate(() => (window as any).__tankBattle.state.tanks.find((t: any) => t.team === 'player' && t.name !== '房主坦克'));
  const guestSelf = await guest.evaluate(() => {
    const d = (window as any).__tankBattle;
    return d.state.tanks.find((t: any) => t.id === d.localId);
  });
  expect(hostGuest.x).toBeGreaterThan(guestBefore.x + 1);
  expect(hostGuest.z).toBeCloseTo(guestBefore.z);
  expect(Math.abs(hostGuest.x - guestSelf.x)).toBeLessThan(0.4);
  expect(Math.abs(hostGuest.z - guestSelf.z)).toBeLessThan(0.4);
  await host.locator('#pauseButton').tap();
  await expect.poll(() => guest.evaluate(() => (window as any).__tankBattle.state.paused)).toBe(true);
  await guest.screenshot({ path: 'artifacts/multiplayer-guest.png' });
  expect(errors).toEqual([]);
  await guestContext.close();
  await hostContext.close();
});
